apiVersion: apps/v1
kind: Deployment
metadata:
  name: health-med-api
spec:
  replicas: 3
  selector:
    matchLabels:
      app: health-med-api
  template:
    metadata:
      labels:
        app: health-med-api
    spec:
      containers:
      - name: health-med-api
        image: jorgeoliveira/healthmedsys:latest
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: health-med-service
spec:
  type: ClusterIP
  selector:
    app: health-med-api
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
