name: WorkFlow - HackaThon
on:  
  push:
    branches: [ "master" ]

jobs:
  test:
    name: Job para executar os testes
    runs-on: ubuntu-latest
    steps:   
      - name: Checkout do código fonte
        uses: actions/checkout@v3
        
      - name: Configurar o .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '7.0.x'

      - name: Restaurar dependências
        run: dotnet restore HealthMedSys.sln

      - name: Executar testes
        run: dotnet test HMS.Tests/HMS.Tests.csproj --configuration Release --no-build --verbosity normal --no-restore

  build:
    name: Job para gerar o build, gerar imagem e publicar imagem no Docker Hub.
    runs-on: ubuntu-latest  
    needs: test
    steps:   
      - name: Checkout do código fonte
        uses: actions/checkout@v3
        
      - name: Login no Docker Hub
        uses: docker/login-action@v3.0.0
        with:            
          username: 'jorgeoliveira'        
          password: ${{ secrets.SECRET }}

      - name: Build e Push da Imagem Docker para o Docker Hub
        uses: docker/build-push-action@v5.1.0
        with:
          context: .
          tags: 'jorgeoliveira/healthmedsys:latest'
          push: true
